### ISSUE TITLE
[epic] Guide v2 providing an intro and overview of claims

### ISSUE THREAD

**Issue by rufuspollock** [rufuspollock/awesome-crypto-critique#193]
## Acceptance

* [ ] OVERALL: Each claim featured on guide is in "good" state i.e. clear thesis and evaluation (that we are happy with)
* [x] Database of all claims
* [ ] Finalize the prioritized claims
  * [x] Meta
    * [x] What does a claim page look like (at least key part) **✅2022-09-14 #196 **
    * [x] For each claim do summary and evaluation etc
  * [ ] Each claim
    * [x] Neo-metallism YY **✅2022-09-14 PR/commit + (finally) https://web3.lifeitself.us/notes/neo-metallism**
    * [x] Crypto is a new and better payment system YY **✅ 2022-09-16 branch merged https://web3.lifeitself.us/claims/is-better-payments**
    * [ ] Payment system resistant to state e.g. for dissidents YY  **🚧2022-09-14 commit  https://github.com/life-itself/web3/pull/199/commits/1e615c78cb9a30853977a2273b070fec955c12ae site: [../notes/bitcoin-as-anti-authoritarian.md](https://web3.lifeitself.us/notes/bitcoin-as-anti-authoritarian)**
    * [ ] Unregulated trading in securities is desirable YY **🚧2022-09-15 commit https://github.com/life-itself/web3/commit/c7c28503a725a77d8aa0ee64d33c008733242b45 site: [../notes/are-crypto-tokens-securities](https://web3.lifeitself.us/notes/are-crypto-tokens-securities)**
    * [ ] Opportunity for gain YY **🚧2022-09-16 commit https://github.com/life-itself/web3/commit/43c130600314741f71cd0a2ffce5c63467182da2 site: [../claims/opportunity-for-gain.md](https://web3.lifeitself.org/claims/opportunity-for-gain)**
    * [ ] Resource public goods and the commons especially in a voluntary way e.g. gitcoin (software), removing plastic from ocean, increasing the cost of carbon YY **🚧 latest commit 2022-09-20 https://github.com/life-itself/web3/pull/204/commits/189917a1604b61e45a86895bd789425900a85373 site: [..claims/can-solve-collective-action-problem.md](https://web3.lifeitself.org/claims/can-solve-collective-action-problem)**
    * [ ] Better system for managing transactions in all assets (Priority tbd)
    * [ ] HyperFinancialization: You can turn all your interests and commitments into (tradeable) tokens. (Priority tbd)
    * [ ] Crypto mining has a significant environmental impact Y **🚧 commit 2022-09-20 https://github.com/life-itself/web3/commit/e1f5479574fa4117d38f39ad0b3a152e66657be1 site: [../claims/is-environmental-footprint](https://web3.lifeitself.org/claims/is-environmental-footprint)**
    * [ ] Crypto investments negative-sum games Y **🚧 commit 2022-09-21 https://github.com/life-itself/web3/commit/eff5593b5c579b2201ef304486eaf1033bde6166**
    * [ ] Crypto is predatory investments Y
* [ ] Integrate into guide
* [ ] Final tidying

## Tasks

* [x] #181 - first pass on redoing the guide around claims. Intro etc done and most of the way there 
* [x] Review that

Next steps

* [x] #192 
* [x] Prioritize claims to "finalize" i.e. summary and evaluation **✅2022-09-13 see the YY column in the sheet**

Next steps - 2022-09-14

* [x] Improve further payment rails ✅ **2022-09-14 pull requested committed https://github.com/life-itself/web3/commit/c4464ed439c398c1ea6a231007f5f849bdb51865**
* [x] improve further anti-authoritarian **✅2022-09-14 see https://github.com/life-itself/web3/pull/199/commits/1e615c78cb9a30853977a2273b070fec955c12ae**
* [ ] Analyse claims in "make money" into coggle
* [ ] split up fintech incrementalism
  * [ ] Better banking and finance: Real-time, always on, cheaper, decentralized ... 
    * [x] Better payments systems ✅ [/claims/is-better-payments.md](https://web3.lifeitself.us/claims/is-better-payments)
    * [ ] Better system for managing transactions in all assets (e.g. equities too) - Extension of better payment rail to e.g. stock markets, commodities etc
  * [ ] (priority tbd) HyperFinancialization claim: we want programmable money, or to create tokens for everything. Meme-onomics is the future. You can turn all your interests and commitments into (tradeable) tokens. The next step for homo-economicus
  * [ ] Optional: something on central bank digital currencies ? (do they just relate to better payment rail)

Sharing

* [ ] Announce

### Neo-metallism ✅ https://web3.lifeitself.us/notes/neo-metallism 

- [x] Deep dive will become primary claim page ✅ https://web3.lifeitself.us/notes/neo-metallism 
- [x] Merge claim page into deep dive
- [x] Write up summary
- [x] Write up evaluation
- [x] Remove old claim page
- [x] Add evidence people claim this

### Crypto is a new and better payment system ✅ https://web3.lifeitself.us/claims/is-better-payments

- [x] use claims page as the main page ✅ https://web3.lifeitself.us/claims/is-better-payments
- [x] update content **✅2022-09-14 see https://github.com/life-itself/web3/commit/88244f61e6b6122ae904e8fd81064ad9a517de7a**
	  - [x] create a steel-man summary 
	  - [x] create evaluation  
	  - [x] evidence of people claiming
- [x] Review **✅2022-09-14 see comments on https://github.com/life-itself/web3/commit/88244f61e6b6122ae904e8fd81064ad9a517de7a**
  - [x] Eilidh makes changes in response to comments: ✅ **pull requested committed https://github.com/life-itself/web3/commit/c4464ed439c398c1ea6a231007f5f849bdb51865**
  - [x] Eilidh make is-better-payments Zotero folder ✅ **[References](https://www.zotero.org/groups/4600269/web3/collections/FYMMIQPV) and [Evidence](https://www.zotero.org/groups/4600269/web3/collections/3D8M7EH6)**
  - [x] @rufuspollock review

### Payment system resistant to state e.g. for dissidents 🚧 https://web3.lifeitself.us/notes/bitcoin-as-anti-authoritarian

- [x] Deep dive will become primary claim page
- [x] Merge claim page into deep dive
- [x] update content **✅2022-09-14 see https://github.com/life-itself/web3/pull/199/commits/1e615c78cb9a30853977a2273b070fec955c12ae**
	- [x] Write up summary
	- [x] Write up evaluation
	- [x] Add evidence people claim this
	- [x] Merge references
- [x] Review @rufuspollock 
- [ ] Eilidh respond to comments **https://github.com/life-itself/web3/commit/04fdbd7dfcd1d2ec9942996988b04fd53c50d1ee**
- [ ] Remove old claim pages /claims/is-transnational-payment.md & /claims/is-authoritarianism.md
  - [x] Remove links to old claim pages
- [ ] Zotero folders ✅ **[References](https://www.zotero.org/groups/4600269/web3/collections/YLCGQPGN) and [evidence](https://www.zotero.org/groups/4600269/web3/collections/QRSFJ8M2)**
  - [x] make zotero folder for references ✅ **https://www.zotero.org/groups/4600269/web3/collections/YLCGQPGN**
    - [x] merge references from [/claims/is-transnational-payment](https://web3.lifeitself.us/claims/is-transnational-payment) and [/claims/is-authoritarianism](https://web3.lifeitself.us/claims/is-authoritarianism) ✅ 
  - [x] make folder for evidence ✅  **https://www.zotero.org/groups/4600269/web3/collections/QRSFJ8M2**
- [x] generate bibliography from references folder and paste into primary claim page ✅ 

### Crypto is enabling more and better financial products and a more efficient market ✅ https://web3.lifeitself.us/notes/fintech-incrementalism-and-responsible-innovation 

- [x] Split up claims from fintech deep dive ✅ **[coggle](https://coggle.it/diagram/YyGhGOfA2wMrF6cQ/t/web3-claim-analysis-for-fintech-incrementalism-steel-man)**
- [ ] Create claims pages:
  - [ ] Better banking and finance: Real-time, always on, cheaper, decentralized ... 
    - [x] Better payment systems ✅ **[/claims/is-better-payments.md](https://web3.lifeitself.us/claims/is-better-payments)**
    - [ ] Better systems for processing transactions in any assets eg stocks
  - [ ] Hyperfinancialozation: we want programmable money, or to create tokens for everything. Meme-onomics is the future. You can turn all your interests and commitments into (tradeable) tokens. The next step for homo-economicus
- [ ] For each claim
  - [ ] Write up steel man summary
  - [ ] Write up evaluation
  - [ ] Add evidence people claim this
  - [ ] change title
- [ ] Review @rufuspollock 

### Make money from trading or investing in crypto

- [x] Split up claims from [market fundamentalism](https://web3.lifeitself.us/notes/market-fundamentalism) deep dive ✅ **[coggle](https://coggle.it/diagram/YyLhIufA2wMrvzyl/t/trading-crypto)**
- [x] Create opportunity for gain claim page ✅ **2022-09-15 commit: https://github.com/life-itself/web3/commit/071e13985a86ab3a3ef7c566ec0106bf82515b9a**
  - [x] Write up summary
  - [x] Write up evaluation
  - [x] Add evidence people claim this
  - [x] Create Zotero folders ✅ **[references](https://www.zotero.org/groups/4600269/web3/collections/ARJYRSAD) and [evidence](https://www.zotero.org/groups/4600269/web3/collections/P2Z333EZ)**
  - [ ] Review @rufuspollock 

### Resource public goods and the commons especially in a voluntary way e.g. gitcoin (software), removing plastic from ocean, increasing the cost of carbon **🚧 latest commit 2022-09-20 https://github.com/life-itself/web3/pull/204/commits/189917a1604b61e45a86895bd789425900a85373**

- [x] create claim page
- [x] Write up summary
- [x] Write up evaluation
- [x] Add evidence people claim this
- [ ] Rufus review

### Crypto mining has a significant environmental impact **🚧 commit 2022-09-20 https://github.com/life-itself/web3/commit/e1f5479574fa4117d38f39ad0b3a152e66657be1**

- [ ] Deep dive will become primary claim page
- [ ] Merge claim page into deep dive
- [ ] Write up summary
- [ ] Write up evaluation
- [ ] Remove old claim page
  - [ ] Remove links to old claim page
- [ ] Add evidence people claim this

### Crypto investments negative-sum games and predatory investments

- [ ] Deep dive will become primary claim page
- [ ] Merge claim page into deep dive
- [ ] Write up summary
- [ ] Write up evaluation
- [ ] Remove old claim page
  - [ ] Remove links to old claim page
- [ ] Add evidence people claim this

### Claims to remove

Claims not needed/relevant or aren't really claims.

* [x] https://web3.lifeitself.us/claims/is-weird-culture
* [ ] https://web3.lifeitself.us/claims/is-well-defined - can merge with https://web3.lifeitself.us/concepts/web3 (to extent appropriate)

**Comment by EilidhRoss1** [comment]
@rufuspollock I realized after pushing my edits to the fintech claim page that I didn't change the title to reflect the claim (currently still has the title from the deep dive). So flagging that as a TODO, wasn't sure if I could go back and make that edit after submitting the pull request.

**Comment by rufuspollock** [comment]
@EilidhRoss1 great job. can you add links to commit or pull request for changes so it is easier for me to review them. I've started adding above so you can see what i mean.
